spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root
  redis:
    # Redis 单机单实例
    database: 0
    host: 192.168.31.78
    port: 6379
    password: root
    # Redis 哨兵模式
#    database: 0
#    password: root
#    sentinel:
#      master: mymaster
#      nodes: 192.168.2.247:26379,192.168.2.192:26379,192.168.2.237:26379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
